services:
  jarvis:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "pnpm run start:dev"
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    env_file:
      - .env
    ports:
      - "3000:3000"
    privileged: true
    volumes:
      # - .:/usr/src/app/jarvis
      # - type: tmpfs
      - service-account:/usr/src/app/credentials

    working_dir: /usr/src/app/jarvis

volumes:
  service-account: