name: Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create service account file
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" > service-account.json

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: shareef945/jarvis:latest
          platforms: linux/arm64
          cache-from: type=registry,ref=shareef945/jarvis:buildcache
          cache-to: type=registry,ref=shareef945/jarvis:buildcache,mode=max

      - name: Deploy to SAI Server
        run: |
          # Deploy new version
          ssh shareef@192.168.100.3 '
            cd /home/shareef/apps/jarvis && \
            docker compose pull && \
            docker compose up -d --remove-orphans
          '
      - name: Send Telegram notification (success)
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 Production Deployment Status

            Environment: Production
            Status: Success ✅

      - name: Send Telegram notification (failure)
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ❌ Production Deployment Status

            Environment: Production
            Status: Failed ❌
            ⚠️ Check GitHub Actions for detailed error logs.