name: Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Local Registry
        uses: docker/login-action@v1
        with:
          registry: 192.168.100.2:5000
          username: ${{ secrets.REGISTRY_USERNAME }}  # if required
          password: ${{ secrets.REGISTRY_PASSWORD }}  # if required

      - name: Create service account file
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" > service-account.json

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 192.168.100.2:5000/telegram-bot:latest
          platforms: linux/amd64,linux/arm64

      - name: Trigger Coolify Redeploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_AUTH_TOKEN }}" \
            "https://deploy.saitechnology.co/api/v1/deploy?uuid=g040c8o&force=false"
